name: Feature request 💡
description: >-
  Use this template to propose new features.
title: '[Feat:] '
labels:
  - phase / exploring
  - type / feature
body:
  - type: input
    id: component
    attributes:
      label: Component
      description: Write the component name issue is related with.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: >-
        A clear and concise description of the problem. E.g. I'm always
        frustrated when [...]
  - type: textarea
    id: describe
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered.
  - type: dropdown
    id: help
    attributes:
      label: Are you able to assist to bring the feature to reality?
      options:
        - 'no'
        - 'yes'
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or already existing solutions about the feature request here.
