import React from "react";

import Pill, { IPillProps } from "@components/atoms/Pill";
import Checkbox, { ICheckboxProps } from "@components/molecules/Checkbox";
import { ISwitchProps } from "@components/molecules/Switch";
import { Row, TableCol } from "@components/molecules/Table/type";

export const defaultColumns: TableCol<Row>[] = [
    {
        id: "expand",
        isVisible: true,
        order: 0,
        enableGlobalFilter: false,
        type: "Expand",
        accessorKey: "expand",
        header: ""
    },
    {
        id: "rowCheckbox",
        isVisible: true,
        order: 0,
        enableGlobalFilter: false,
        type: "RowCheckbox",
        accessorKey: "rowCheckbox"
    },
    {
        id: "graph",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        enableColumnFilter: false,
        type: "Graph",
        accessorKey: "graph",
        enableSorting: false,
        editable: false,
        copyable: false,
        header: "Graph",
        rowCellRenderer: () => <div>here will be Image</div>,
        footer: (props) => props.column.id
    },
    {
        id: "title",
        order: 2,
        isVisible: true,
        type: "Text",
        disabled: true,
        accessorFn: (row) => row.Text,
        enableSorting: true,
        editable: true,
        copyable: true,
        isColumnFilterDisabled: true,
        header: "Title",
        footer: (props) => props.column.id
    },
    {
        id: "number",
        isVisible: true,
        order: 1,
        enableGlobalFilter: true,
        type: "Number",
        accessorFn: (row) => row.Number,
        enableSorting: true,
        editable: true,
        copyable: true,
        header: "Number",
        footer: (props) => props.column.id
    },
    {
        id: "description",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "LongText",
        accessorFn: (row) => row.LongText,
        editable: true,
        copyable: true,
        enableSorting: false,
        header: "Description",
        footer: (props) => props.column.id
    },
    {
        id: "dropdown",
        isVisible: true,
        order: 2,
        enableGlobalFilter: true,
        type: "Dropdown",
        accessorFn: (row) => row.Dropdown,
        editable: true,
        copyable: true,
        enableSorting: true,
        enablePopoverFilter: false,
        header: "Dropdown",
        footer: (props) => props.column.id
    },
    {
        id: "status",
        isVisible: true,
        order: 2,
        enableGlobalFilter: true,
        type: "Status",
        accessorFn: (row) => row.Status,
        enableColumnFilter: false,
        enablePopoverFilter: true,
        isPopoverFilterDisabled: true,
        rowCellRenderer: (props) => <Pill {...(props as IPillProps)} />,
        enableSorting: true,
        copyable: false,
        header: "Status",
        footer: (props) => props.column.id
    },
    {
        id: "pill",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "Pill",
        accessorFn: (row) => row.Pill,
        enableColumnFilter: false,
        editable: false,
        copyable: false,
        enableSorting: true,
        rowCellRenderer: (props) => <Pill {...(props as IPillProps)} />,
        header: "Pill",
        footer: (props) => props.column.id
    },
    {
        id: "icon",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "Icon",
        accessorFn: (row) => row.Icon,
        enableColumnFilter: false,
        editable: false,
        copyable: false,
        enableSorting: true,
        header: "Icon",
        footer: (props) => props.column.id
    },
    {
        id: "flag",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "Flag",
        accessorFn: (row) => row.Flag,
        enableColumnFilter: false,
        editable: false,
        copyable: false,
        enableSorting: true,
        header: "Flag",
        footer: (props) => props.column.id
    },
    {
        id: "checkbox",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "Checkbox",
        accessorFn: (row) => (row.Checkbox as ICheckboxProps).checked,
        enableColumnFilter: false,
        editable: true,
        copyable: false,
        enableSorting: true,
        rowCellRenderer: (props) => <Checkbox readOnly {...(props as ICheckboxProps)} />,
        enablePopoverFilter: true,
        header: "Checkbox",
        footer: (props) => props.column.id
    },
    {
        id: "switch",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "Switch",
        accessorFn: (row) => ((row.Switch as ISwitchProps).checked ? "On" : "Off"),
        enableColumnFilter: false,
        editable: true,
        copyable: false,
        enableSorting: true,
        enablePopoverFilter: true,
        filterOptions: ["On", "Off"],
        header: "Switch",
        footer: (props) => props.column.id
    }
];

export const withPinnedColumns: TableCol<Row>[] = [
    {
        id: "rowCheckbox",
        isVisible: true,
        order: 0,
        enableGlobalFilter: false,
        type: "RowCheckbox",
        accessorKey: "rowCheckbox"
    },
    {
        id: "graph",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        enableColumnFilter: false,
        type: "Graph",
        accessorKey: "graph",
        enableSorting: false,
        editable: false,
        copyable: false,
        header: "Graph",
        rowCellRenderer: () => <div>here will be Image</div>,
        footer: (props) => props.column.id
    },
    {
        id: "title",
        order: 2,
        isVisible: true,
        type: "Text",
        disabled: true,
        accessorFn: (row) => row.Text,
        enableSorting: true,
        editable: true,
        copyable: true,
        isColumnFilterDisabled: true,
        header: "Title",
        footer: (props) => props.column.id
    },
    {
        id: "number",
        isVisible: true,
        order: 1,
        enableGlobalFilter: true,
        type: "Number",
        accessorFn: (row) => row.Number,
        enableSorting: true,
        editable: true,
        copyable: true,
        header: "Number",
        footer: (props) => props.column.id
    },
    {
        id: "description",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "LongText",
        accessorFn: (row) => row.LongText,
        editable: true,
        copyable: true,
        enableSorting: false,
        header: "Description",
        footer: (props) => props.column.id
    },
    {
        id: "dropdown",
        isVisible: true,
        order: 2,
        enableGlobalFilter: true,
        type: "Dropdown",
        accessorFn: (row) => row.Dropdown,
        editable: true,
        copyable: true,
        enableSorting: true,
        enablePopoverFilter: false,
        header: "Dropdown",
        footer: (props) => props.column.id
    },
    {
        id: "status",
        isVisible: true,
        order: 2,
        enableGlobalFilter: true,
        type: "Status",
        accessorFn: (row) => row.Status,
        enableColumnFilter: false,
        enablePopoverFilter: true,
        isPopoverFilterDisabled: true,
        rowCellRenderer: (props) => <Pill {...(props as IPillProps)} />,
        enableSorting: true,
        copyable: false,
        header: "Status",
        footer: (props) => props.column.id
    },
    {
        id: "pill",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "Pill",
        accessorFn: (row) => row.Pill,
        enableColumnFilter: false,
        editable: false,
        copyable: false,
        enableSorting: true,
        rowCellRenderer: (props) => <Pill {...(props as IPillProps)} />,
        header: "Pill",
        footer: (props) => props.column.id
    },
    {
        id: "icon",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "Icon",
        accessorFn: (row) => row.Icon,
        enableColumnFilter: false,
        editable: false,
        copyable: false,
        enableSorting: true,
        header: "Icon",
        footer: (props) => props.column.id
    },
    {
        id: "flag",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "Flag",
        accessorFn: (row) => row.Flag,
        enableColumnFilter: false,
        editable: false,
        copyable: false,
        enableSorting: true,
        header: "Flag",
        footer: (props) => props.column.id
    },
    {
        id: "checkbox",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "Checkbox",
        accessorFn: (row) => (row.Checkbox as ICheckboxProps).checked,
        enableColumnFilter: false,
        editable: true,
        copyable: false,
        enableSorting: true,
        rowCellRenderer: (props) => <Checkbox readOnly {...(props as ICheckboxProps)} />,
        enablePopoverFilter: true,
        header: "Checkbox",
        footer: (props) => props.column.id
    },
    {
        id: "switch",
        isVisible: true,
        order: 2,
        enableGlobalFilter: false,
        type: "Switch",
        accessorFn: (row) => ((row.Switch as ISwitchProps).checked ? "On" : "Off"),
        enableColumnFilter: false,
        editable: true,
        copyable: false,
        enableSorting: true,
        enablePopoverFilter: true,
        filterOptions: ["On", "Off"],
        header: "Switch",
        footer: (props) => props.column.id
    }
];

export const withGroupedColumns: TableCol<Row>[] = [
    {
        id: "groupName",
        header: "Group Name",
        accessorKey: "groupName",
        order: 0,
        type: "Text",
        footer: (props) => props.column.id,
        enableSorting: false,
        enableGlobalFilter: false,
        enableColumnFilter: false,
        columns: [
            {
                id: "expand",
                isVisible: true,
                order: 0,
                enableGlobalFilter: false,
                type: "Expand",
                accessorKey: "expand",
                header: null
            },
            {
                id: "rowCheckbox",
                isVisible: true,
                order: 0,
                enableGlobalFilter: false,
                type: "RowCheckbox",
                accessorKey: "rowCheckbox",
                header: null
            },
            {
                id: "graph",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                enableColumnFilter: false,
                type: "Graph",
                accessorKey: "graph",
                enableSorting: false,
                editable: false,
                copyable: false,
                header: "Graph",
                rowCellRenderer: () => <div>here will be Image</div>,
                footer: (props) => props.column.id
            },
            {
                id: "title",
                order: 2,
                isVisible: true,
                type: "Text",
                disabled: true,
                accessorFn: (row) => row.Text,
                enableSorting: true,
                editable: true,
                copyable: true,
                isColumnFilterDisabled: true,
                header: "Title",
                footer: (props) => props.column.id
            },
            {
                id: "number",
                isVisible: true,
                order: 1,
                enableGlobalFilter: true,
                type: "Number",
                accessorFn: (row) => row.Number,
                enableSorting: true,
                isSortingDisabled: true,
                editable: true,
                copyable: true,
                header: "Number",
                footer: (props) => props.column.id
            },
            {
                id: "description",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "LongText",
                accessorFn: (row) => row.LongText,
                editable: true,
                copyable: true,
                enableSorting: false,
                header: "Description",
                footer: (props) => props.column.id
            },
            {
                id: "dropdown",
                isVisible: true,
                order: 2,
                enableGlobalFilter: true,
                type: "Dropdown",
                accessorFn: (row) => row.Dropdown,
                editable: true,
                copyable: true,
                enableSorting: true,
                enablePopoverFilter: false,
                header: "Dropdown",
                footer: (props) => props.column.id
            },
            {
                id: "status",
                isVisible: true,
                order: 2,
                enableGlobalFilter: true,
                type: "Status",
                accessorFn: (row) => row.Status,
                enableColumnFilter: false,
                enablePopoverFilter: true,
                isPopoverFilterDisabled: true,
                rowCellRenderer: (props) => <Pill {...(props as IPillProps)} />,
                enableSorting: true,
                copyable: false,
                header: "Status",
                footer: (props) => props.column.id
            },
            {
                id: "pill",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "Pill",
                accessorFn: (row) => row.Pill,
                enableColumnFilter: false,
                editable: false,
                copyable: false,
                enableSorting: true,
                rowCellRenderer: (props) => <Pill {...(props as IPillProps)} />,
                header: "Pill",
                footer: (props) => props.column.id
            },
            {
                id: "icon",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "Icon",
                accessorFn: (row) => row.Icon,
                enableColumnFilter: false,
                editable: false,
                copyable: false,
                enableSorting: true,
                header: "Icon",
                footer: (props) => props.column.id
            },
            {
                id: "flag",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "Flag",
                accessorFn: (row) => row.Flag,
                enableColumnFilter: false,
                editable: false,
                copyable: false,
                enableSorting: true,
                header: "Flag",
                footer: (props) => props.column.id
            },
            {
                id: "checkbox",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "Checkbox",
                accessorFn: (row) => (row.Checkbox as ICheckboxProps).checked,
                enableColumnFilter: false,
                editable: true,
                copyable: false,
                enableSorting: true,
                rowCellRenderer: (props) => <Checkbox readOnly {...(props as ICheckboxProps)} />,
                enablePopoverFilter: true,
                header: "Checkbox",
                footer: (props) => props.column.id
            },
            {
                id: "switch",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "Switch",
                accessorFn: (row) => ((row.Switch as ISwitchProps).checked ? "On" : "Off"),
                enableColumnFilter: false,
                editable: true,
                copyable: false,
                enableSorting: true,
                enablePopoverFilter: true,
                filterOptions: ["On", "Off"],
                header: "Switch",
                footer: (props) => props.column.id
            }
        ] as TableCol<Row>[]
    }
];
