import { RowData, TableCol } from "@components/molecules/Table/type";

export const defaultColumns: TableCol<RowData>[] = [
    {
        id: "groupName",
        header: "Group Name",
        accessorKey: "groupName",
        order: 0,
        type: "text",
        footer: (props) => props.column.id,
        enableSorting: false,
        enableGlobalFilter: false,
        enableColumnFilter: false,
        columns: [
            {
                id: "expand",
                isVisible: true,
                order: 0,
                enableGlobalFilter: false,
                type: "expand",
                accessorKey: "expand",
                header: null
            },
            {
                id: "rowCheckbox",
                isVisible: true,
                order: 0,
                enableGlobalFilter: false,
                type: "rowCheckbox",
                accessorKey: "rowCheckbox",
                header: null
            },
            {
                id: "graph",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "graph",
                accessorKey: "graph",
                editable: false,
                copyable: false,
                header: "Graph",
                cell: (info) => info.getValue(),
                footer: (props) => props.column.id
            },
            {
                id: "title",
                order: 2,
                isVisible: false,
                type: "text",
                accessorFn: (row) => row.text?.data,
                enableSorting: true,
                editable: true,
                copyable: true,
                cell: (cell) => cell,
                header: "Title",
                footer: (props) => props.column.id
            },
            {
                id: "number",
                isVisible: true,
                order: 1,
                enableGlobalFilter: true,
                type: "number",
                accessorFn: (row) => row.number?.data,
                enableSorting: true,
                editable: true,
                copyable: true,
                cell: (info) => info,
                header: "Number",
                footer: (props) => props.column.id
            },
            {
                id: "description",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "longText",
                accessorFn: (row) => row.text?.data,
                editable: true,
                copyable: true,
                enableSorting: true,
                cell: (info) => info.getValue(),
                header: "Description",
                footer: (props) => props.column.id
            },
            {
                id: "dropdown",
                isVisible: true,
                order: 2,
                enableGlobalFilter: true,
                type: "dropdown",
                accessorFn: (row) => row.dropdown?.data,
                editable: true,
                copyable: true,
                enableSorting: true,
                enablePopoverFilter: true,
                cell: (info) => info.getValue(),
                header: "Dropdown",
                footer: (props) => props.column.id
            },
            {
                id: "status",
                isVisible: true,
                order: 2,
                enableGlobalFilter: true,
                type: "status",
                accessorFn: (row) => row.status?.data,
                enablePopoverFilter: true,
                enableSorting: true,
                copyable: false,
                cell: (info) => info.getValue(),
                header: "Status",
                footer: (props) => props.column.id
            },
            {
                id: "pill",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "pill",
                accessorFn: (row) => row.pill?.data,
                editable: false,
                copyable: false,
                enableSorting: true,
                cell: (info) => info.getValue(),
                header: "Pill",
                footer: (props) => props.column.id
            },
            {
                id: "icon",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "icon",
                accessorFn: (row) => row.icon?.data,
                editable: false,
                copyable: false,
                enableSorting: true,
                cell: (info) => info.getValue(),
                header: "Icon",
                footer: (props) => props.column.id
            },
            {
                id: "flag",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "flag",
                accessorFn: (row) => row.flag?.data,
                editable: false,
                copyable: false,
                enableSorting: true,
                cell: (info) => info.getValue(),
                header: "Flag",
                footer: (props) => props.column.id
            },
            {
                id: "checkbox",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "checkbox",
                accessorFn: (row) => row.checkbox?.data,
                editable: true,
                copyable: false,
                enableSorting: true,
                enablePopoverFilter: true,
                cell: (info) => info.getValue(),
                header: "Checkbox",
                footer: (props) => props.column.id
            },
            {
                id: "switch",
                isVisible: true,
                order: 2,
                enableGlobalFilter: false,
                type: "switch",
                accessorFn: (row) => (row.switch?.data ? "On" : "Off"),
                editable: true,
                copyable: false,
                enableSorting: true,
                enablePopoverFilter: true,
                filterOptions: ["On", "Off"],
                cell: (info) => info.getValue(),
                header: "Switch",
                footer: (props) => props.column.id
            }
        ] as TableCol<RowData>[]
    }
];
