name: Notify Reviewers
on:
    pull_request:
        branches: ["release/*"]
jobs:
    send_notification:
        runs-on: ubuntu-latest
        steps:
            - name: Get Reviewers
            id: reviewers
            run: |
                echo "::set-output name=reviewers::$(echo '${{ github.event.pull_request.requested_reviewers.*.login }}' | tr ' ' '\n')"

            - name: Accumulate Reviewers
            id: accumulate_reviewers
            run: |
                REVIEWERS=${{ steps.reviewers.outputs.reviewers }}
                REVIEWERS_LIST=""

                # Iterate over the reviewers and accumulate bullet list
                for reviewer in $REVIEWERS; do
                    REVIEWERS_LIST="$REVIEWERS_LIST- $reviewer\n"
                done

                # Set the accumulated reviewers list as an output
                echo "::set-output name=reviewers_list::$REVIEWERS_LIST"

            - name: Send Notification
            env:
                INTERNAL_NOTIFICATION_CHANNEL_API_ENDPOINT: ${{ secrets.INTERNAL_NOTIFICATION_CHANNEL_API_ENDPOINT }}
            run: |
                PR_ID=${{ github.event.pull_request.number }}
                PR_URL=${{ github.event.pull_request.html_url }}
                PR_AUTHOR=${{ github.event.pull_request.user.login }}
                REVIEWERS=${{ github.event.pull_request.requested_reviewers.*.login }}

                MESSAGE="@channel\nNew Pull Request: [#$PR_ID]($PR_URL) by @$PR_AUTHOR\nRequested Reviewers: $REVIEWERS"

                curl -X POST -H "Content-Type: application/json" -d "{\"text\": \"$MESSAGE\"}" $INTERNAL_NOTIFICATION_CHANNEL_API_ENDPOINT